### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'get_values'

### ISSUE THREAD

**Issue by Aruun** [ACloudGuru-Resources/Course_AWS_Certified_Machine_Learning#4]
In algorithms lab, after converting the required values to categorical values.  When trying to execute the below shell, facing the following issue.

![image](https://user-images.githubusercontent.com/12800407/98545394-6db8fa00-22bb-11eb-97f0-efc065e01438.png)

I am using conda_python3 kernel and m1.t2.medium notebook instance.

Initial Analysis:
Googled the above issue and found the get_values method is deprecated and searching for the alternative method.  Could you please help me to find the alternative method.

Thank you!

**Comment by brocktubre** [comment]
Hi @Aruun, I have fixed this issue by replacing `.get_values()` with `.to_numpy()`. Here is the commit: https://github.com/ACloudGuru-Resources/Course_AWS_Certified_Machine_Learning/commit/931951ce8e16e433e29f081afc01b9b2ae5dade4

**Comment by Aruun** [comment]
Thanks for the great help @brocktubre
