### ISSUE TITLE
The method get_image_uri has been renamed in sagemaker>=2.

### ISSUE THREAD

**Issue by Aruun** [ACloudGuru-Resources/Course_AWS_Certified_Machine_Learning#5]
Issue:
Facing following issue, when trying to run algorithms lab.  Please find the following screenshot:
![image](https://user-images.githubusercontent.com/12800407/98634901-09914700-234a-11eb-8dcd-4279802ae0e6.png).  

Resolution:
from sagemaker import image_uris
container = sagemaker.image_uris.retrieve("xgboost", boto3.Session().region_name, "1.2-1")

Root Cause:
The method get_image_uri has been renamed in sagemaker>=2.

Thank you!

**Comment by Aruun** [comment]
Resolution provided.

**Comment by brocktubre** [comment]
@Aruun I am making changes throughout the entire course for deprecated methods from the SageMaker Python SDK v2.x. THANK YOU for pointing these out and bringing it to my attention. There are more than the ones you have pointed out. I advise going through and "redownloading" the Juypter notebooks that have been updated. 

I have pushed all of the changes. These includes:
- Deprecated `get_image_uri` which is now `image_uri.retrieve`
- Renaming `training_instance_count` to `instance_cout`
- Renaming `training_instance_type` to `instance_type`
- Deprecated `s3_input` which is now `sagemaker.inputs.TrainingInput`
- Renamed `csv_serializer` and `json_deserializer` to `sagemaker.serializers.CSVSerializer()` and `sagemaker.deserializers.JSONDeserializer()` respectively

Please see the changes in the commit here: https://github.com/ACloudGuru-Resources/Course_AWS_Certified_Machine_Learning/commit/ab99654f4c7150a3f8d18b9e35b9d1f696707448

**Comment by Aruun** [comment]
great help @brocktubre .  Thanks much :)
